### ISSUE TITLE
How to register helpers to be compiled 

### ISSUE THREAD

**Issue by mrlove** [mattacular/grunt-handlebars-compiler#13]
Hi,

i was wondering how i can compile templates with the helpers included? There is no option to specify which helpers should be build/compiled in..

Can you help me with that?

Best,
mrlove

**Comment by mattacular** [comment]
Thanks for the report, I will look into a resolution as soon as possible!

On Wednesday, August 5, 2015, Mrlove <notifications@github.com> wrote:

> Hi,
>
> i was wondering how i can compile templates with the helpers included?
> There is no option to specify which helpers should be build/compiled in..
>
> Can you help me with that?
>
> Best,
> mrlove
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattacular/grunt-handlebars-compiler/issues/13>.
>


-- 
Sent from my phone

**Comment by mrlove** [comment]
There is a possible workaround when you are loading the handlebars runtime, than register all helpers and here we go... But thing is, i can not execute templates as standalone, i do always depend on preloaded helpers.. 
But on a long term it becomes quit hard to map the dependency graph by hand... Things get even worse, when you try to maintain stuff like this and you do not have and hood overview about which templates use which helpers..

**Comment by mrlove** [comment]
Are there any news on this issue?

**Comment by mattacular** [comment]
I will look into it this month.
